# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vector_search.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'vector_search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13vector_search.proto\x12\x0cvectorsearch\"?\n\rSearchRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\r\n\x05top_k\x18\x02 \x01(\x05\x12\x0f\n\x07n_probe\x18\x03 \x01(\x05\"(\n\x08Neighbor\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\"9\n\x0eSearchResponse\x12\'\n\x07results\x18\x01 \x03(\x0b\x32\x16.vectorsearch.Neighbor\"\x1f\n\rInsertRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x02\"\x1c\n\x0eInsertResponse\x12\n\n\x02id\x18\x01 \x01(\x03\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"/\n\rUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\nnew_vector\x18\x02 \x03(\x02\"!\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xa2\x02\n\x0cVectorSearch\x12\x43\n\x06Search\x12\x1b.vectorsearch.SearchRequest\x1a\x1c.vectorsearch.SearchResponse\x12\x43\n\x06Insert\x12\x1b.vectorsearch.InsertRequest\x1a\x1c.vectorsearch.InsertResponse\x12\x43\n\x06\x44\x65lete\x12\x1b.vectorsearch.DeleteRequest\x1a\x1c.vectorsearch.DeleteResponse\x12\x43\n\x06Update\x12\x1b.vectorsearch.UpdateRequest\x1a\x1c.vectorsearch.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST']._serialized_start=37
  _globals['_SEARCHREQUEST']._serialized_end=100
  _globals['_NEIGHBOR']._serialized_start=102
  _globals['_NEIGHBOR']._serialized_end=142
  _globals['_SEARCHRESPONSE']._serialized_start=144
  _globals['_SEARCHRESPONSE']._serialized_end=201
  _globals['_INSERTREQUEST']._serialized_start=203
  _globals['_INSERTREQUEST']._serialized_end=234
  _globals['_INSERTRESPONSE']._serialized_start=236
  _globals['_INSERTRESPONSE']._serialized_end=264
  _globals['_DELETEREQUEST']._serialized_start=266
  _globals['_DELETEREQUEST']._serialized_end=293
  _globals['_DELETERESPONSE']._serialized_start=295
  _globals['_DELETERESPONSE']._serialized_end=328
  _globals['_UPDATEREQUEST']._serialized_start=330
  _globals['_UPDATEREQUEST']._serialized_end=377
  _globals['_UPDATERESPONSE']._serialized_start=379
  _globals['_UPDATERESPONSE']._serialized_end=412
  _globals['_VECTORSEARCH']._serialized_start=415
  _globals['_VECTORSEARCH']._serialized_end=705
# @@protoc_insertion_point(module_scope)
